#!/usr/bin/python3.5
# EASY-INSTALL-ENTRY-SCRIPT: 'gemato==11.2','console_scripts','gemato'
__requires__ = 'gemato==11.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('gemato==11.2', 'console_scripts', 'gemato')()
    )
