;;; finder-inf.el --- keyword-to-package mapping
;; Keywords: help
;;; Commentary:
;; Don't edit this file.  It's generated by finder.el

;;; Code:

(defconst finder-package-info '(
    ("abbrev.el"
        "abbrev mode commands for Emacs"
        (abbrev  dumped)
        "lisp/")
    ("about.el"
        "the About The Authors page (shameless self promotion)."
        (extensions)
        "lisp/")
    ("alist.el"
        "utility functions about association-list"
        (alist)
        "lisp/")
    ("apropos.el"
        "apropos commands for users and programmers."
        (help)
        "lisp/")
    ("auto-save.el"
        "Safer autosaving for EFS and tmp."
        (extensions  dumped)
        "lisp/")
    ("auto-show.el"
        "perform automatic horizontal scrolling as point moves"
        (extensions  internal  dumped)
        "lisp/")
    ("autoload.el"
        "maintain autoloads in auto-autoloads files."
        (maint)
        "lisp/")
    ("backquote.el"
        "Full backquote support for elisp.  Reverse compatible too."
        (extensions  dumped)
        "lisp/")
    ("behavior-defs.el"
        "definitions of specific behaviors"
        (internal  dumped)
        "lisp/")
    ("behavior.el"
        "consistent interface onto packages"
        (internal  dumped)
        "lisp/")
    ("blessmail.el"
        "Decide whether movemail needs special privileges."
        (internal)
        "lisp/")
    ("buff-menu.el"
        "buffer menu/tab main function and support functions."
        (frames  extensions  internal  dumped)
        "lisp/")
    ("buffer.el"
        "buffer routines taken from C"
        (internal  dumped)
        "lisp/")
    ("build-report.el"
        "Automatically formatted build reports for XEmacs"
        (internal)
        "lisp/")
    ("byte-optimize.el"
        "the optimization passes of the emacs-lisp byte compiler."
        (internal)
        "lisp/")
    ("bytecomp-runtime.el"
        "byte-compiler support for inlining"
        (internal  dumped)
        "lisp/")
    ("bytecomp.el"
        "compilation of Lisp code into byte code."
        (internal lisp)
        "lisp/")
    ("callers-of-rpt.el"
        "generate call graph of lisp in XEmacs"
        (internal)
        "lisp/")
    ("check-features.el"
        "Do a sanity check on an XEmacs build"
        (internal)
        "lisp/")
    ("cl-extra.el"
        "Common Lisp extensions for XEmacs Lisp (part two)"
        (extensions  dumped)
        "lisp/")
    ("cl-macs.el"
        "Common Lisp extensions for XEmacs Lisp (part four)"
        (extensions)
        "lisp/")
    ("cl-seq.el"
        "Common Lisp extensions for XEmacs Lisp (part three)"
        (extensions  dumped)
        "lisp/")
    ("cl.el"
        "Common Lisp extensions for XEmacs Lisp"
        (extensions  dumped  lisp)
        "lisp/")
    ("cmdloop.el"
        "support functions for the top-level command loop."
        (internal  dumped)
        "lisp/")
    ("code-cmds.el"
        "Commands for manipulating coding systems."
        nil
        "lisp/")
    ("code-files.el"
        "File I/O functions for XEmacs."
        nil
        "lisp/")
    ("code-init.el"
        "Handle coding system default values"
        nil
        "lisp/")
    ("code-process.el"
        "Process coding functions for XEmacs."
        (mule  multilingual  coding system  process)
        "lisp/")
    ("coding.el"
        "Coding-system functions for XEmacs."
        nil
        "lisp/")
    ("compat.el"
        "Mechanism for non-intrusively providing compatibility funs."
        (internal)
        "lisp/")
    ("config.el"
        "access configuration parameters"
        (configure)
        "lisp/")
    ("console.el"
        "miscellaneous console functions not written in C"
        (internal  dumped)
        "lisp/")
    ("cus-dep.el"
        "Find customization dependencies."
        (internal)
        "lisp/")
    ("cus-edit.el"
        "Tools for customizating Emacs and Lisp packages."
        (help  faces)
        "lisp/")
    ("cus-face.el"
        "Support for Custom faces."
        (help  faces)
        "lisp/")
    ("cus-file.el"
        "Manage location of the customize init file"
        (internal)
        "lisp/")
    ("cus-load.el"
        "Batch load all available cus-load files"
        (internal  help  faces)
        "lisp/")
    ("cus-start.el"
        "define customization properties of builtins."
        (internal  dumped)
        "lisp/")
    ("custom-load.el"
        "automatically extracted custom dependencies"
        nil
        "lisp/")
    ("custom.el"
        "tools for declaring and initializing options"
        (help  faces  dumped)
        "lisp/")
    ("derived.el"
        "allow inheritance of major modes"
        (extensions  dumped)
        "lisp/")
    ("descr-text.el"
        "describe text mode"
        (faces  i18n  unicode  multilingual)
        "lisp/")
    ("device.el"
        "miscellaneous device functions not written in C"
        (internal  dumped)
        "lisp/")
    ("diagnose.el"
        "routines for debugging problems in XEmacs"
        (dumped)
        "lisp/")
    ("dialog-gtk.el"
        "Dialog-box support for XEmacs w/GTK primitives"
        (extensions  internal  dumped)
        "lisp/")
    ("dialog-items.el"
        "Dialog-box content for XEmacs"
        (content  gui  internal  dumped)
        "lisp/")
    ("dialog.el"
        "Dialog-box support for XEmacs"
        (extensions  internal  dumped)
        "lisp/")
    ("disass.el"
        "disassembler for compiled Emacs Lisp code"
        (internal)
        "lisp/")
    ("disp-table.el"
        "functions for dealing with char tables."
        (i18n  internal)
        "lisp/")
    ("dragdrop.el"
        "window system-independent Drag'n'Drop support."
        (mouse  gui  dumped)
        "lisp/")
    ("easy-mmode.el"
        "easy definition for major and minor modes"
        (extensions lisp)
        "lisp/")
    ("etags.el"
        "etags facility for Emacs"
        (tools)
        "lisp/")
    ("events.el"
        "event functions for XEmacs."
        (internal  event  dumped)
        "lisp/")
    ("extents.el"
        "miscellaneous extent functions not written in C"
        (internal  dumped)
        "lisp/")
    ("faces.el"
        "Lisp interface to the C \"face\" structure"
        (faces  internal  dumped)
        "lisp/")
    ("files.el"
        "file input and output commands for XEmacs."
        (extensions  dumped)
        "lisp/")
    ("fill.el"
        "fill commands for XEmacs."
        (wp  dumped)
        "lisp/")
    ("find-paths.el"
        "setup various XEmacs paths"
        (internal  dumped)
        "lisp/")
    ("finder.el"
        "topic & keyword-based code finder"
        (help)
        "lisp/")
    ("float-sup.el"
        "detect absence of floating-point support in XEmacs runtime"
        (internal  dumped)
        "lisp/")
    ("font-lock.el"
        "decorating source files with fonts/colors based on syntax"
        (languages  faces)
        "lisp/")
    ("font-menu.el"
        "Managing menus of fonts."
        nil
        "lisp/")
    ("font-mgr.el"
        "Lisp emulation of fontconfig for X fonts."
        nil
        "lisp/")
    ("font.el"
        "New font model"
        (faces)
        "lisp/")
    ("fontcolor.el"
        "Lisp interface to fonts and colors"
        (faces  internal  dumped)
        "lisp/")
    ("fontconfig.el"
        "New font model, NG"
        (faces)
        "lisp/")
    ("fontl-hooks.el"
        "pre-loaded stuff for font-lock."
        nil
        "lisp/")
    ("format.el"
        "read and save files in multiple formats"
        (extensions  dumped)
        "lisp/")
    ("frame.el"
        "multi-frame management independent of window systems."
        (internal  dumped)
        "lisp/")
    ("gdk.el"
        "Import GDK functions into XEmacs"
        (extensions  dumped)
        "lisp/")
    ("generic-widgets.el"
        "Generic UI building"
        (extensions  dumped)
        "lisp/")
    ("glade.el"
        "Import libglade functions into XEmacs"
        (extensions  dumped)
        "lisp/")
    ("glyphs.el"
        "Lisp interface to C glyphs"
        (extensions  internal  dumped)
        "lisp/")
    ("gnome-widgets.el"
        "Import GNOME functions into XEmacs"
        (extensions  dumped)
        "lisp/")
    ("gnome.el"
        "GNOME integration for XEmacs/GTK"
        nil
        "lisp/")
    ("gnuserv.el"
        "Lisp interface code between Emacs and gnuserv"
        (environment  processes  terminals)
        "lisp/")
    ("gpm.el"
        "Support the mouse when emacs run on a Linux console."
        (mouse  terminals)
        "lisp/")
    ("gtk-compose.el"
        "provide compose-key handling to GTK"
        nil
        "lisp/")
    ("gtk-extra.el"
        "Import `GTK+ Extra' widgets into XEmacs"
        (extensions  dumped)
        "lisp/")
    ("gtk-faces.el"
        "GTK-specific face frobnication, aka black magic."
        (extensions  internal  dumped)
        "lisp/")
    ("gtk-ffi.el"
        "Foreign function interface for the GTK object system"
        (extensions  dumped)
        "lisp/")
    ("gtk-file-dialog.el"
        "A nicer file selection dialog for XEmacs w/GTK primitives"
        (extensions  internal)
        "lisp/")
    ("gtk-font-menu.el"
        "Managing menus of GTK fonts."
        nil
        "lisp/")
    ("gtk-glyphs.el"
        "Support for glyphs in Gtk"
        (extensions  internal  dumped)
        "lisp/")
    ("gtk-init.el"
        "initialization code for mswindows"
        nil
        "lisp/")
    ("gtk-marshal.el"
        "regenerate C wrappers for GTK"
        nil
        "lisp/")
    ("gtk-mouse.el"
        "Mouse support for GTK window system."
        (mouse  dumped)
        "lisp/")
    ("gtk-package.el"
        "GTK version of package-ui"
        nil
        "lisp/")
    ("gtk-password-dialog.el"
        "Reading passwords in a dialog"
        (extensions  internal)
        "lisp/")
    ("gtk-select.el"
        "Lisp interface to GTK selections."
        (extensions  dumped)
        "lisp/")
    ("gtk-widget-accessors.el"
        "GTK wrappers for widgets"
        nil
        "lisp/")
    ("gtk-widgets.el"
        "Import GTK functions into XEmacs"
        (extensions  dumped)
        "lisp/")
    ("gtk.el"
        "provide information about GTK wrapping"
        nil
        "lisp/")
    ("gui.el"
        "Basic GUI functions for XEmacs."
        (internal  dumped)
        "lisp/")
    ("gutter-items.el"
        "Gutter content for XEmacs."
        (frames  extensions  internal  dumped)
        "lisp/")
    ("gutter.el"
        "Gutter manipulation for XEmacs."
        (frames  gui  internal  dumped)
        "lisp/")
    ("hash-table.el"
        "hash-table utility functions"
        (internal  dumped)
        "lisp/")
    ("help-macro.el"
        "Makes command line help such as help-for-help"
        nil
        "lisp/")
    ("help.el"
        "help commands for XEmacs."
        (help  internal  dumped)
        "lisp/")
    ("hyper-apropos.el"
        "Hypertext emacs lisp documentation interface."
        (lisp  tools  help  docs  matching)
        "lisp/")
    ("indent.el"
        "indentation commands for XEmacs"
        (lisp  languages  tools  dumped)
        "lisp/")
    ("info.el"
        "info package for Emacs."
        (help)
        "lisp/")
    ("isearch-mode.el"
        "Incremental search minor mode."
        (extensions  dumped)
        "lisp/")
    ("iso8859-1.el"
        "Set case table for Latin 1"
        (internal  dumped)
        "lisp/")
    ("itimer-autosave.el"
        "Autosave functions with itimers"
        (internal  dumped)
        "lisp/")
    ("keydefs.el"
        "Define standard keybindings."
        (internal  dumped)
        "lisp/")
    ("keymap.el"
        "Keymap functions for XEmacs."
        (internals  dumped)
        "lisp/")
    ("ldap.el"
        "LDAP support for Emacs"
        (help comm)
        "lisp/")
    ("lib-complete.el"
        "Completion on the lisp search path"
        (lisp  extensions  dumped)
        "lisp/")
    ("lisp-mnt.el"
        "minor mode for Emacs Lisp maintainers"
        (docs  maint)
        "lisp/")
    ("lisp-mode.el"
        "Lisp mode, and its idiosyncratic commands."
        (lisp  languages  dumped)
        "lisp/")
    ("lisp.el"
        "Lisp editing commands for XEmacs"
        (lisp  languages  dumped)
        "lisp/")
    ("list-mode.el"
        "Major mode for buffers containing lists of items"
        (extensions  dumped)
        "lisp/")
    ("loaddefs.el"
        "define standard autoloads of other files"
        (internal)
        "lisp/")
    ("loadhist.el"
        "lisp functions for working with feature groups"
        (internal  dumped)
        "lisp/")
    ("loadup.el"
        "load up standardly loaded Lisp files for XEmacs."
        (internal  dumped)
        "lisp/")
    ("make-docfile.el"
        "Cache docstrings in external file"
        (internal)
        "lisp/")
    ("map-ynp.el"
        "General-purpose boolean question-asker."
        (lisp  extensions  dumped)
        "lisp/")
    ("menubar-items.el"
        "Menubar and popup-menu content for XEmacs."
        (frames  extensions  internal  dumped)
        "lisp/")
    ("menubar.el"
        "Menubar support for XEmacs"
        (internal  extensions  dumped)
        "lisp/")
    ("minibuf.el"
        "Minibuffer functions for XEmacs"
        (internal  dumped)
        "lisp/")
    ("misc.el"
        "miscellaneous functions for XEmacs"
        (extensions  dumped)
        "lisp/")
    ("mode-motion.el"
        "Mode-specific mouse-highlighting of text."
        (internal  mouse  dumped)
        "lisp/")
    ("modeline.el"
        "modeline hackery."
        (extensions  dumped)
        "lisp/")
    ("mouse.el"
        "window system-independent mouse support."
        (mouse  dumped)
        "lisp/")
    ("movemail.el"
        "move mail spool to a place where XEmacs can munge it"
        (internal  dumped)
        "lisp/")
    ("msw-faces.el"
        "mswindows-specific face stuff."
        nil
        "lisp/")
    ("msw-font-menu.el"
        "Managing menus of mswindows fonts."
        nil
        "lisp/")
    ("msw-glyphs.el"
        "Support for glyphs in ms windows"
        (extensions  internal  dumped)
        "lisp/")
    ("msw-init.el"
        "initialization code for mswindows"
        nil
        "lisp/")
    ("msw-mouse.el"
        "Mouse support for MS Windows."
        (mouse  dumped)
        "lisp/")
    ("msw-select.el"
        "Lisp interface to mswindows selections."
        (extensions  dumped)
        "lisp/")
    ("multicast.el"
        "lisp frontend for multicast connections in XEmacs"
        (dumped comm processes)
        "lisp/")
    ("mwheel.el"
        "Mouse support for MS intelli-mouse type mice"
        (mouse)
        "lisp/")
    ("newcomment.el"
        "(un)comment regions of buffers"
        (comment uncomment)
        "lisp/")
    ("next-error.el"
        "Next error support framework"
        (internal)
        "lisp/")
    ("obsolete.el"
        "obsoleteness support"
        (internal  dumped)
        "lisp/")
    ("occur.el"
        "Show all lines in the current buffer containing a match for REGEXP."
        (internal)
        "lisp/")
    ("package-admin.el"
        "Installation and Maintenance of XEmacs packages"
        (internal)
        "lisp/")
    ("package-get.el"
        "Retrieve XEmacs package"
        (internal)
        "lisp/")
    ("package-info.el"
        "Generate information about an XEmacs package"
        (internal)
        "lisp/")
    ("package-net.el"
        "Installation and Maintenance of XEmacs packages"
        (internal)
        "lisp/")
    ("packages.el"
        "Low level support for XEmacs packages"
        (internal  lisp  dumped)
        "lisp/")
    ("page.el"
        "page motion commands for Emacs"
        (extensions  dumped)
        "lisp/")
    ("paragraphs.el"
        "paragraph and sentence parsing"
        (wp  dumped)
        "lisp/")
    ("paths.el"
        "define pathnames for use by various Emacs commands."
        (internal  dumped)
        "lisp/")
    ("picture.el"
        "\"Picture mode\" -- editing using quarter-plane screen model."
        nil
        "lisp/")
    ("post-gc.el"
        "post-gc actions"
        (internal  dumped)
        "lisp/")
    ("printer.el"
        "support for hard-copy printing in XEmacs"
        (printer  printing  internal  dumped)
        "lisp/")
    ("process.el"
        "commands for subprocesses; split out of simple.el"
        (internal  processes  dumped)
        "lisp/")
    ("raw-process.el"
        "In a raw temacs, load stuff so processes work"
        (internal)
        "lisp/")
    ("rect.el"
        "rectangle functions for XEmacs."
        (internal)
        "lisp/")
    ("regexp-opt.el"
        "generate efficient regexps to match strings"
        (strings  regexps  extensions)
        "lisp/")
    ("register.el"
        "register commands for Emacs"
        (internal  dumped)
        "lisp/")
    ("replace.el"
        "search and replace commands for XEmacs."
        (dumped  matching)
        "lisp/")
    ("resize-minibuffer.el"
        "dynamically resize minibuffer to display entire contents"
        (minibuffer  window  frames  display)
        "lisp/")
    ("scrollbar.el"
        "Scrollbar support for XEmacs"
        (internal  extensions  dumped)
        "lisp/")
    ("select.el"
        "Lisp interface to windows selections."
        (extensions  dumped)
        "lisp/")
    ("setup-paths.el"
        "setup various XEmacs paths"
        (internal  dumped)
        "lisp/")
    ("shadow.el"
        "Locate Emacs Lisp file shadowings."
        (lisp)
        "lisp/")
    ("simple.el"
        "basic editing commands for XEmacs"
        (lisp  extensions  internal  dumped)
        "lisp/")
    ("site-load.el"
        "Template file for site-wide XEmacs customization"
        (internal)
        "lisp/")
    ("sound.el"
        "Loading sound files in XEmacs"
        (internal)
        "lisp/")
    ("special-mode.el"
        "Special major mode to view specially formatted data"
        (dumped)
        "lisp/")
    ("specifier.el"
        "Lisp interface to specifiers"
        (internal  dumped)
        "lisp/")
    ("startup.el"
        "process XEmacs shell arguments"
        (internal  dumped)
        "lisp/")
    ("subr.el"
        "basic lisp subroutines for XEmacs"
        (extensions  dumped  internal)
        "lisp/")
    ("symbol-syntax.el"
        "find chars with symbol syntax"
        (matching)
        "lisp/")
    ("symbols.el"
        "functions for working with symbols and symbol values"
        (internal)
        "lisp/")
    ("syntax-ppss.el"
        "helper functions to find syntactic context"
        (internal)
        "lisp/")
    ("syntax.el"
        "Syntax-table hacking stuff, moved from syntax.c"
        nil
        "lisp/")
    ("test-harness.el"
        "Run Emacs Lisp test suites."
        (testing)
        "lisp/")
    ("text-mode.el"
        "text mode, and its idiosyncratic commands."
        (wp  dumped)
        "lisp/")
    ("text-props.el"
        "implements properties of characters"
        (extensions  wp  faces  dumped)
        "lisp/")
    ("toolbar-items.el"
        "Static initialization of XEmacs toolbar"
        (frames  dumped)
        "lisp/")
    ("toolbar.el"
        "Toolbar support for XEmacs"
        (extensions  internal  dumped)
        "lisp/")
    ("tty-init.el"
        "initialization code for tty's"
        (terminals  dumped)
        "lisp/")
    ("undo-stack.el"
        "An \"undoable stack\" object."
        (extensions  dumped)
        "lisp/")
    ("unicode.el"
        "Unicode support -*- coding: utf-8; -*-"
        (multilingual  unicode)
        "lisp/")
    ("update-elc-2.el"
        "Recompile remaining .el files, post-dumping"
        (internal)
        "lisp/")
    ("update-elc.el"
        "Bytecompile out-of-date dumped files, pre-dumping"
        (internal)
        "lisp/")
    ("userlock.el"
        "handle file access contention between multiple users"
        (internal)
        "lisp/")
    ("version.el"
        "Record version number of Emacs."
        (internal  dumped)
        "lisp/")
    ("view-less.el"
        "Minor mode for browsing files with keybindings like `less'"
        (wp  unix)
        "lisp/")
    ("wid-browse.el"
        "Functions for browsing widgets."
        (extensions)
        "lisp/")
    ("wid-edit.el"
        "Functions for creating and using widgets."
        (extensions)
        "lisp/")
    ("widget.el"
        "a library of user interface components."
        (help  extensions  faces  hypermedia  dumped)
        "lisp/")
    ("widgets-gtk.el"
        "Embedded widget support for XEmacs w/GTK primitives"
        (extensions  internal  dumped)
        "lisp/")
    ("win32-native.el"
        "Lisp routines when running on native MS Windows."
        (mouse  dumped)
        "lisp/")
    ("window-xemacs.el"
        "XEmacs window commands aside from those written in C."
        (frames  extensions  dumped)
        "lisp/")
    ("window.el"
        "XEmacs window commands aside from those written in C."
        (frames  extensions  dumped)
        "lisp/")
    ("x-compose.el"
        "Compose-key processing in XEmacs"
        (i18n)
        "lisp/")
    ("x-faces.el"
        "X-specific face frobnication, aka black magic."
        (extensions  internal  dumped)
        "lisp/")
    ("x-font-menu.el"
        "Managing menus of X fonts."
        nil
        "lisp/")
    ("x-init.el"
        "initialization code for X windows"
        (terminals  dumped)
        "lisp/")
    ("x-misc.el"
        "miscellaneous X functions."
        (extensions  dumped)
        "lisp/")
    ("x-mouse.el"
        "Mouse support for X window system."
        (mouse  dumped)
        "lisp/")
    ("x-scrollbar.el"
        "scrollbar resourcing and such."
        (extensions  dumped)
        "lisp/")
    ("x-select.el"
        "Lisp interface to X Selections."
        (extensions  dumped)
        "lisp/")
    ("x-win-sun.el"
        "runtime initialization for Sun X servers and keyboards"
        (terminals)
        "lisp/")
    ("x-win-xfree86.el"
        "runtime initialization for XFree86 servers"
        (terminals)
        "lisp/")
))

(provide 'finder-inf)

;;; finder-inf.el ends here
